# Site settings
title: SC AufRuhr e.V.
contactemail: webmaster@sc-aufruhr.de
url: http://www.sc-aufruhr.de/
description: "Der schwul-lesbische Sportverein im Ruhrgebiet"
skills: "Der schwul-lesbische Sportverein im Ruhrgebiet"
meta_author: SC AufRuhr e.V.

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 333333 #80B3FF
  primary-rgb: "153,153,153" #"128,179,255"
  secondary: aaaaaa #FD6E8A
  secondary-dark: 777777 #A2122F

# Footer settings
footer:
  copyright: SC AufRuhr e. V.
  location: Postadresse
  social: Socialmedia
  credits: Gestaltung

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/SCAufRuhr

# Postal address (add as many lines as necessary)
address:
  - line: SC AufRuhr e. V.
  - line: c/o Aidshilfe Bochum e.V.
  - line: Große Beckstr. 12
  - line: 44787 Bochum

# Credits content
credits: '<a href="moxie.de" target="_blank">moxie.de</a>'

# Build settings
markdown: kramdown
permalink: pretty
